=== lckobe123/awesome-spring/spring-test/src/main/resources/xml/students.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--<schema> 元素是每一个 XML Schema 的根元素：-->
<!--xmlns指明本xsd中定义的元素都是来定义在这个名称空间下的，在别的名称空间中自然不能够引用，
这个名称空间显然需要唯一，使用域名是比较好的选择-->
<!--targetNamespace呢不同于xmlns,他是指定本xsd中使用到的元素都是来自于这个名称空间，而不是定义的元素,
同时规定使用此名称空间下的元素必须使用前缀 xs:-->
<!--一般而言xmlns和targetNamespace需要相同-->
<!-- xmlns:students="http://www.github.com.cn/schema/students"
这个是给这个名称空间起了一个别名,用于在xpath中选择元素-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.github.com.cn/schema/students"
           xmlns="http://www.github.com.cn/schema/students"
           xmlns:students="http://www.github.com.cn/schema/students"
           elementFormDefault="qualified">

    <!--定义学生类型-->
    <xs:complexType name="studentType">
        <xs:sequence>
            <xs:element name="no" type="xs:string"/>
            <xs:element name="mobile" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="school" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!--定义校长类型-->
    <xs:complexType name="principalType">
        <xs:sequence>
            <xs:element name="master" type="xs:string"/>
            <xs:element name="vice" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!--定义文档结构-->
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <!--这里定义的先后顺序也是xml中必须遵循的顺序-->
                <xs:element name="principal" type="principalType"/>
                <xs:element name="student" maxOccurs="unbounded" type="studentType"/>
            </xs:sequence>
        </xs:complexType>
        <!--students下面不允许有多个id相同的student属性-->
        <xs:unique name="studentUnique">
            <xs:selector xpath="students:student"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== lckobe123/awesome-spring/spring-test/src/main/resources/xml/students.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--定义一系列的学生-->
<!--xmlns 指明本文档中使用的元素都在这个名称空间下被申明的-->
<!--xsi:schemaLocation 作用是指定本xml使用xsd的位置，他有两个值,第一个是xmlns，第二个是xsd的名字
xsd中必须以第一个值作为默认的xmlns,否则会找不到元素，
指明本xml中使用的元素都在以这个url作为namespace的xsd中定义了-->
<students xmlns="http://www.github.com.cn/schema/students"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.github.com.cn/schema/students students.xsd">

    <principal id="1207010166">
        <master>郑强</master>
        <vice>袁小泉</vice>
        <vice>刘永义</vice>
        <vice>成大正</vice>
    </principal>

    <student id="1207010166">
        <no>12070101166</no>
        <mobile>18798624470</mobile>
        <name>陶江航</name>
        <school>贵州大学</school>
    </student>

    <student id="1207010167">
        <no>12070101166</no>
        <mobile>18798624470</mobile>
        <name>陶江航</name>
        <school>贵州大学</school>
    </student>

    <student id="1207010168">
        <no>12070101166</no>
        <mobile>18798624470</mobile>
        <name>陶江航</name>
        <school>贵州大学</school>
    </student>

    <student id="1207010169">
        <no>12070101166</no>
        <mobile>18798624470</mobile>
        <name>陶江航</name>
        <school>贵州大学</school>
    </student>

</students>
